/********************************************************************
* UBOscCint.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error UBOscCint.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableUBOscCint();
extern void G__cpp_setup_inheritanceUBOscCint();
extern void G__cpp_setup_typetableUBOscCint();
extern void G__cpp_setup_memvarUBOscCint();
extern void G__cpp_setup_globalUBOscCint();
extern void G__cpp_setup_memfuncUBOscCint();
extern void G__cpp_setup_funcUBOscCint();
extern void G__set_cpp_environmentUBOscCint();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "FluxRW.hh"
#include "FluxRWnubar.hh"
#include "LorentzVectorLight.hh"
#include "NtupleReprocessing.hh"
#include "UBOsc-TypeDef.hh"
#include "UBOsc.hh"
#include "Utils.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__UBOscCintLN_TString;
extern G__linked_taginfo G__UBOscCintLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__UBOscCintLN_string;
extern G__linked_taginfo G__UBOscCintLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__UBOscCintLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__UBOscCintLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__UBOscCintLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__UBOscCintLN_TH1D;
extern G__linked_taginfo G__UBOscCintLN_lar1;
extern G__linked_taginfo G__UBOscCintLN_lar1cLcLFluxRW;
extern G__linked_taginfo G__UBOscCintLN_lar1cLcLFluxRWnubar;
extern G__linked_taginfo G__UBOscCintLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__UBOscCintLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__UBOscCintLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__UBOscCintLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__UBOscCintLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__UBOscCintLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__UBOscCintLN_TElementActionTlEdoublegR;
extern G__linked_taginfo G__UBOscCintLN_TElementPosActionTlEdoublegR;
extern G__linked_taginfo G__UBOscCintLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__UBOscCintLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__UBOscCintLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__UBOscCintLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__UBOscCintLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__UBOscCintLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__UBOscCintLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__UBOscCintLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__UBOscCintLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__UBOscCintLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__UBOscCintLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__UBOscCintLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__UBOscCintLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__UBOscCintLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__UBOscCintLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__UBOscCintLN_TVector3;
extern G__linked_taginfo G__UBOscCintLN_TLorentzVector;
extern G__linked_taginfo G__UBOscCintLN_gan;
extern G__linked_taginfo G__UBOscCintLN_gancLcLLorentzVectorLight;
extern G__linked_taginfo G__UBOscCintLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__UBOscCintLN_TFile;
extern G__linked_taginfo G__UBOscCintLN_TMatrixTRow_constlEdoublegR;
extern G__linked_taginfo G__UBOscCintLN_TMatrixTlEdoublegR;
extern G__linked_taginfo G__UBOscCintLN_TMatrixTSymlEdoublegR;
extern G__linked_taginfo G__UBOscCintLN_TMatrixTRowlEdoublegR;
extern G__linked_taginfo G__UBOscCintLN_TMatrixTSparselEdoublegR;
extern G__linked_taginfo G__UBOscCintLN_TMatrixTSparseRow_constlEdoublegR;
extern G__linked_taginfo G__UBOscCintLN_TMatrixTSparseRowlEdoublegR;
extern G__linked_taginfo G__UBOscCintLN_TMatrixTDiag_constlEdoublegR;
extern G__linked_taginfo G__UBOscCintLN_TMatrixTColumn_constlEdoublegR;
extern G__linked_taginfo G__UBOscCintLN_TMatrixTSparseDiag_constlEdoublegR;
extern G__linked_taginfo G__UBOscCintLN_TTree;
extern G__linked_taginfo G__UBOscCintLN_TBranch;
extern G__linked_taginfo G__UBOscCintLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__UBOscCintLN_TMatrixTFlat_constlEdoublegR;
extern G__linked_taginfo G__UBOscCintLN_TMatrixTSub_constlEdoublegR;
extern G__linked_taginfo G__UBOscCintLN_TMatrixTColumnlEdoublegR;
extern G__linked_taginfo G__UBOscCintLN_TMatrixTDiaglEdoublegR;
extern G__linked_taginfo G__UBOscCintLN_TMatrixTFlatlEdoublegR;
extern G__linked_taginfo G__UBOscCintLN_TMatrixTSublEdoublegR;
extern G__linked_taginfo G__UBOscCintLN_TMatrixTSparseDiaglEdoublegR;
extern G__linked_taginfo G__UBOscCintLN_lar1cLcLUtils;
extern G__linked_taginfo G__UBOscCintLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__UBOscCintLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__UBOscCintLN_vectorlEgancLcLLorentzVectorLightcOallocatorlEgancLcLLorentzVectorLightgRsPgR;
extern G__linked_taginfo G__UBOscCintLN_reverse_iteratorlEvectorlEgancLcLLorentzVectorLightcOallocatorlEgancLcLLorentzVectorLightgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__UBOscCintLN_lar1cLcLNtupleReprocessing;
extern G__linked_taginfo G__UBOscCintLN_UBOsc;

/* STUB derived class for protected member access */
